apiVersion: v1
kind: Pod
metadata:
  name: fastapi
  namespace: test
  labels:
    app: fastapi
spec:
  containers:
  - name: fastapi
    image: docker.io/joan77/k8s-dst-eval-fastapi:latest
    command: ["uvicorn"]
    args: ["main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    envFrom:
    - secretRef:
        name: mysql-user
    volumeMounts:
    - mountPath: /app
      name: app-volume
  volumes:
  - name: app-volume
    #hostPath:
    #  path: C:/Users/joan/Documents/DataScience_MLOPS/Project/mlops_rakuten2/k8s_deployment/api/app
    #  type: Directory
    persistentVolumeClaim:
      claimName: pvc-app
