apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: test
  labels:
    app: fastapi
spec:
  selector:
    app: fastapi
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
