apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-app
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath-storage
  volumeName: pv-app