version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
    volumes:
      - ./:/app/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:80/health"]
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 20s

  test:
    build:
      context: ./
      dockerfile: Dockerfile.app_basis
    depends_on:
      - api
        # condition: service_healthy
    environment:
      - RUNNING_IN_DOCKER=true
    volumes:
      - ./:/app/
      - ./reports:/app/reports
    command: sh -c "ls -R /app/tests && pytest --html=/app/reports/report.html && tail -n 1000 /app/reports/report.html"
