FROM python:3.9-slim

WORKDIR /app

COPY requirements_api.txt .

ENV RUNNING_IN_DOCKER=true
ENV PYTHONPATH=/app

RUN pip install --no-cache-dir -r requirements_api.txt

COPY main.py /app/main.py
COPY pretrain_models /app/pretrain_models
COPY models_api /app/models_api
COPY testData/ /app/testData
COPY tests/ /app/tests


CMD ["sh", "-c", "pytest tests/app_basis/test_app_basis.py | tee tests/app_basis/test_app_basis.log"]

