services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:80"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--", "/app/wait_for_it.sh localhost:80 -t 120", "--", "pytest", "/app/tests/app_basis/test_app_basis.py"]
    deploy:
      resources:
        limits:
          memory: 4g 
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    

  tests_app_basis:
    build:
      context: .
      dockerfile: Dockerfile.app_basis
    container_name: tests_app_basis
    volumes:
      - .:/app
    environment:
      - RUNNING_IN_DOCKER=true
      - PYTHONPATH=/app
    depends_on:
      - api
        # condition: service_healthy
    command: ["pytest", "tests/app_basis/test_app_basis.py"]
    working_dir: /app