FROM python:3.9-slim

WORKDIR /app

COPY requirements_api.txt .

ENV RUNNING_IN_DOCKER=true
ENV PYTHONPATH=/app

RUN pip install --no-cache-dir -r requirements_api.txt

COPY main.py /app/main.py
COPY pretrain_models /app/pretrain_models
COPY models_api /app/models_api
COPY testData /app/testData
COPY tests/* /app/tests/*

CMD ["sh", "-c", "pytest tests/app_basis/test_app_basis.py | tee tests/app_basis/test_app_basis.log"]

# COPY tests/app_basis/data/mock_fine_tune.csv /app/tests/data/data/mock_fine_tune.csv
# COPY tests/app_basis/data/mock_evaluate_missing_filepath.csv /app/tests/data/mock_evaluate_missing_filepath.csv
# COPY tests/app_basis/data/mock_evaluate_missing_labels.csv /app/tests/data/mock_evaluate_missing_labels.csv
# COPY tests/app_basis/data/mock_image.jpg /app/tests/data/mock_image.jpg
# COPY tests/app_basis/data/mock_text.txt /app/tests/data/mock_text.txt
# COPY tests/app_basis/data/image_1263597046_product_3804725264.jpg /app/tests/data/image_1263597046_product_3804725264.jpg
# COPY tests/app_basis/data/image_1008141237_product_436067568.jpg /app/tests/data/image_1008141237_product_436067568.jpg
# COPY tests/app_basis/data/image_938777978_product_201115110.jpg /app/tests/data/image_938777978_product_201115110.jpg
# COPY tests/app_basis/data/image_457047496_product_50418756.jpg /app/tests/data/image_457047496_product_50418756.jpg
# COPY tests/app_basis/data/image_1077757786_product_278535884.jpg /app/tests/data/image_1077757786_product_278535884.jpg