version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 20s
      timeout: 30s
      retries: 20
      start_period: 5s

  test:
    build:
      context: ./
      dockerfile: Dockerfile.app_basis
    depends_on:
      api:
        condition: service_healthy
    environment:
      - RUNNING_IN_DOCKER=true
    volumes:
      - ./api/tests:/app/tests
    command: sh -c "pytest tests/ --html=report.html && tail -n 1000 report.html"
