version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
    volumes:
      - ./:/app/
    healthcheck:
      test: ["CMD", "curl", "--silent --fail http://0.0.0.0:80/health || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 60s

  test:
    build:
      context: ./
      dockerfile: Dockerfile.app_basis
    depends_on:
      api:
        condition: service_started
    environment:
      - RUNNING_IN_DOCKER=true
    command: sh -c "ls -R /app/tests && mkdir /app/reports && pytest --html=/app/reports/report.html && tail -n 1000 /app/reports/report.html"
    volumes:
      - ./:/app/
      - ./reports:/app/reports
