name: Python CI on Push

on: [push]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black pytest

    - name: Run Flake8
      run: |
        flake8  --verbose --show-source
      continue-on-error: true

    - name: Run Black
      run: black --check .
      continue-on-error: true

    - name: Check for changes
      id: git_diff
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git diff --exit-code || echo "has_changes=true" >> $GITHUB_ENV

    - name: Commit and push changes
      if: env.has_changes == 'true'
      run: |
        git add .
        git commit -m "Apply Black formatting"
        git push

    - name: Run unit tests
      run: pytest
