name: CI - Run API and Tests

on:
  push:
    branches:
      - main
      - feature/unit_tests_fixed
  pull_request:
    branches:
      - main
      - feature/unit_tests_fixed

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: List files in repository
      run: ls -R

    - name: Download release asset
      run: |
        curl -L https://github.com/jo77Lu/mlops_rakuten2/releases/download/model/gold_vgg16.h5 > api/pretrain_models/gold_vgg16.h5

    - name: Start API with Docker Compose
      run: docker-compose -f api/docker-compose.yml up -d --build api

    - name: Grant execution rights to script
      run: chmod +x api/wait_for_it.sh

    - name: Show Docker Compose logs
      run: docker-compose -f api/docker-compose.yml logs --follow api

    - name: List running Docker containers
      run: docker ps -a

    - name: Wait for API to be ready
      run: api/wait_for_it.sh api:80 -t 120

    - name: Run tests and generate HTML report
      run: pytest api/tests/ --html=report.html

    - name: Upload HTML report
      uses: actions/upload-artifact@v2
      with:
        name: pytest-html-report
        path: report.html

    - name: Display part of HTML report in the log
      run: |
        echo "Displaying last 100 lines of HTML report:"
        tail -n 100 report.html

    - name: Stop Docker Compose services
      run: docker-compose down
