name: CI - Run API and Tests

on:
  push:
    branches:
      - main
      - feature/unit_tests_fixed
  pull_request:
    branches:
      - main
      - feature/unit_tests_fixed

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: List files in repository
      run: ls -R

    - name: Start API with Docker Compose
      run: docker-compose -f api/docker-compose.yml up -d --build api

    - name: Wait for API to be ready
      run: api/wait_for_it.sh localhost:80 -t 60

    - name: Run tests and generate HTML report
      run: pytest --html=report.html

    - name: Upload HTML report
      uses: actions/upload-artifact@v2
      with:
        name: pytest-html-report
        path: report.html

    - name: Display part of HTML report in the log
      run: |
        echo "Displaying last 100 lines of HTML report:"
        tail -n 100 report.html

    - name: Stop Docker Compose services
      run: docker-compose down
