name: CI - Run API and Tests

on:
  push:
    branches:
      - main
      - feature/unit_tests_fixed
  pull_request:
    branches:
      - main
      - feature/unit_tests_fixed

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: Download release asset
      run: |
        curl -L -o api/pretrain_models/gold_vgg16.h5 \
         https://github.com/indira893/ModelRakutenMLOps/releases/download/modelvgg/gold_vgg16.h5

    - name: List files in repository
      run: ls -R

  
    - name: Start API and run tests with Docker Compose
      run: docker-compose -f api/docker-compose.yml up --abort-on-container-exit --build

  
    - name: Copy the HTML test report from the test container
      run: docker cp $(docker-compose ps -q test):/app/report.html report.html

  
    - name: Upload HTML report
      uses: actions/upload-artifact@v2
      with:
        name: pytest-html-report
        path: report.html

  
    - name: Display part of HTML report in the log
      run: |
        echo "Displaying last 100 lines of HTML report:"
        tail -n 1000 report.html

    - name: Stop Docker Compose services
      run: docker-compose down
