apiVersion: v1
kind: Service
metadata:
  name: mysqlservice
  namespace: test
spec:
  clusterIP: 10.43.0.42
  # type: NodePort
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 3307
    targetPort: 3306
    # nodePort: 30000
